#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MAINTAINERS_FILE="${ROOT_DIR}/metadata/maintainers.env"
REPO_FILE="${ROOT_DIR}/metadata/repository.env"
OUTPUT_EN="${ROOT_DIR}/README.md"
OUTPUT_ZH="${ROOT_DIR}/README.zh.md"

[[ -f "${MAINTAINERS_FILE}" ]] || { echo "Metadata file missing: ${MAINTAINERS_FILE}" >&2; exit 1; }
[[ -f "${REPO_FILE}" ]] || { echo "Metadata file missing: ${REPO_FILE}" >&2; exit 1; }

# shellcheck disable=SC1090
source "${MAINTAINERS_FILE}"
# shellcheck disable=SC1090
source "${REPO_FILE}"

: "${MAINTAINER_NAME:?Missing MAINTAINER_NAME}"
: "${MAINTAINER_EMAIL:?Missing MAINTAINER_EMAIL}"
: "${GITHUB_SLUG:=}"

declare -a product_dirs=()
while IFS= read -r -d '' dir; do
  product_dirs+=("${dir}")
done < <(find "${ROOT_DIR}/products" -mindepth 1 -maxdepth 1 -type d -print0)

mapfile -t sorted_products < <(printf '%s\n' "${product_dirs[@]}" | xargs -r -n1 basename | sort)

table_en=""
table_zh=""

for product_name in "${sorted_products[@]}"; do
  product_file="${ROOT_DIR}/products/${product_name}/product.env"
  state_file="${ROOT_DIR}/products/${product_name}/state.env"
  [[ -f "${product_file}" ]] || continue

  unset PRODUCT_NAME APP_ID BRANCH TITLE DESCRIPTION HOMEPAGE UPSTREAM_REPO RELEASE_ASSET CURRENT_VERSION CURRENT_BUNDLE_URL
  # shellcheck disable=SC1090
  source "${product_file}"
  if [[ -f "${state_file}" ]]; then
    # shellcheck disable=SC1090
    source "${state_file}"
  fi

  version="${CURRENT_VERSION:-pending}"
  upstream_name="${UPSTREAM_REPO##*/}"
  description="${DESCRIPTION:-}"
  description="${description//$'\n'/ }"
  description="${description//|/\\|}"

  workflow_badge="N/A"
  if [[ -n "${GITHUB_SLUG}" ]]; then
    badge_url="https://img.shields.io/github/actions/workflow/status/${GITHUB_SLUG}/sync-and-publish.yml?branch=main&logo=github&label=sync"
    link_url="https://github.com/${GITHUB_SLUG}/actions/workflows/sync-and-publish.yml"
    workflow_badge="[![Sync Status](${badge_url})](${link_url})"
  fi

  table_en+="| \`${PRODUCT_NAME}\` | \`${APP_ID}\` | ${description} | \`${upstream_name}\` | ${version} | ${workflow_badge} |"$'\n'
  table_zh+="| \`${PRODUCT_NAME}\` | \`${APP_ID}\` | ${description} | \`${upstream_name}\` | ${version} | ${workflow_badge} |"$'\n'
done

table_en="${table_en%$'\n'}"
table_zh="${table_zh%$'\n'}"

cat > "${OUTPUT_EN}" <<EOF
<!-- This file is auto-generated by scripts/build-readme.sh. Do not edit manually. -->

# flatpak-auto

Automation toolkit for maintaining a reusable Flatpak repository with GitHub Actions.

## Overview
- Detect upstream releases per product via \`products/<name>/upstream.sh\`.
- Download Flatpak release bundles from distributed upstream projects.
- Import bundles into one shared OSTree repository.
- Generate \`.flatpakrepo\` and per-product \`.flatpakref\` files.
- Publish the repository to \`gh-pages\`.

## Maintainers
- ${MAINTAINER_NAME} \`<${MAINTAINER_EMAIL}>\`

## Repository
- Remote name: \`${REMOTE_NAME}\`
- Default branch: \`${DEFAULT_BRANCH}\`
- Runtime repo: \`${RUNTIME_REPO}\`

## Products
| Product | App ID | Description | Upstream | Version | Sync Status |
| --- | --- | --- | --- | --- | --- |
${table_en}

Regenerate this README after metadata changes with \`scripts/build-readme.sh\`.
EOF

cat > "${OUTPUT_ZH}" <<EOF
<!-- 该文件由 scripts/build-readme.sh 自动生成，请勿手动编辑。 -->

# flatpak-auto

使用 GitHub Actions 自动维护可复用 Flatpak 仓库的工具集。

## 项目概览
- 通过 \`products/<name>/upstream.sh\` 检测各个上游项目的新版本。
- 从分散的上游项目下载 Flatpak release bundle。
- 将 bundle 导入统一的 OSTree 仓库。
- 生成共享的 \`.flatpakrepo\` 与每个产品对应的 \`.flatpakref\`。
- 发布到 \`gh-pages\`。

## 维护者
- ${MAINTAINER_NAME} \`<${MAINTAINER_EMAIL}>\`

## 仓库信息
- Remote 名称：\`${REMOTE_NAME}\`
- 默认分支：\`${DEFAULT_BRANCH}\`
- Runtime 仓库：\`${RUNTIME_REPO}\`

## 产品列表
| Product | App ID | Description | Upstream | Version | Sync Status |
| --- | --- | --- | --- | --- | --- |
${table_zh}

元数据变更后可运行 \`scripts/build-readme.sh\` 重新生成 README。
EOF

echo "README.md and README.zh.md regenerated."
